// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using NUnit.Framework;
using Settings;

namespace UnitTests.Selenium
{

    [TestFixture]
    public class CatalogProject01CreateNewTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> Vars { get; private set; }
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            Vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
            driver.Dispose();
        }
        [Test]
        public void CatalogProject01CreateNew()
        {
            driver.Navigate().GoToUrl(Params.Url);


            driver.FindElement(By.XPath("//a[contains(@href, '/catalog')]")).Click();

            Wait();

            driver.FindElement(By.XPath("//button[contains(.,' Створити')]")).Click();
            driver.FindElement(By.XPath("(//input[@type='text'])[2]")).SendKeys("Test project");
            driver.FindElement(By.XPath("(//input[@type='text'])[4]")).SendKeys("Test project");
            driver.FindElement(By.CssSelector(".checkbox:nth-child(5) > span")).Click();
            driver.FindElement(By.CssSelector(".ico-save")).Click();
            driver.FindElement(By.XPath("//button[contains(.,'Скасувати')]")).Click();

            Wait();

            {
                WebDriverWait wait = new(driver, TimeSpan.FromSeconds(5));
                wait.Until(driver => driver.FindElements(By.XPath("//span[contains(.,'Test project')]")).Count > 0);
            }

            void Wait()
            {
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(2);
            }
        }
    }


}